version: '3.3'
services:
  backend1:
    image: polarlightning/bitcoind:0.21.1
    container_name: polar-n1-backend1
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    hostname: backend1
    command: >-
      bitcoind -server=1 -regtest=1
      -rpcauth=polaruser:5e5e98c21f5c814568f8b55d83b23c1c$$066b03f92df30b11de8e4b1b1cd5b1b4281aa25205bd57df9be82caf97a05526
      -debug=1 -zmqpubrawblock=tcp://0.0.0.0:28334
      -zmqpubrawtx=tcp://0.0.0.0:28335 -txindex=1 -dnsseed=0 -upnp=0
      -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0 -rpcport=18443 -rest -listen=1
      -listenonion=0 -fallbackfee=0.0002
    volumes:
      - ./volumes/backend1:/home/bitcoin/.bitcoin
    expose:
      - '18443'
      - '18444'
      - '28334'
      - '28335'
    ports:
      - '18443:18443'
      - '19444:18444'
      - '28334:28334'
      - '29335:28335'
    networks:
      - blockspaces
networks:
  blockspaces: